// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockplan

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
	"github.com/tuanta7/chasingpaper/internal/repository/store"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreatePlan provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePlan(ctx context.Context, arg store.CreatePlanParams) (store.Plan, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlan")
	}

	var r0 store.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreatePlanParams) (store.Plan, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, store.CreatePlanParams) store.Plan); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, store.CreatePlanParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreatePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlan'
type MockRepository_CreatePlan_Call struct {
	*mock.Call
}

// CreatePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.CreatePlanParams
func (_e *MockRepository_Expecter) CreatePlan(ctx interface{}, arg interface{}) *MockRepository_CreatePlan_Call {
	return &MockRepository_CreatePlan_Call{Call: _e.mock.On("CreatePlan", ctx, arg)}
}

func (_c *MockRepository_CreatePlan_Call) Run(run func(ctx context.Context, arg store.CreatePlanParams)) *MockRepository_CreatePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 store.CreatePlanParams
		if args[1] != nil {
			arg1 = args[1].(store.CreatePlanParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreatePlan_Call) Return(plan store.Plan, err error) *MockRepository_CreatePlan_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockRepository_CreatePlan_Call) RunAndReturn(run func(ctx context.Context, arg store.CreatePlanParams) (store.Plan, error)) *MockRepository_CreatePlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlan provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPlan(ctx context.Context, id pgtype.UUID) (store.Plan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlan")
	}

	var r0 store.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (store.Plan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) store.Plan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(store.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlan'
type MockRepository_GetPlan_Call struct {
	*mock.Call
}

// GetPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) GetPlan(ctx interface{}, id interface{}) *MockRepository_GetPlan_Call {
	return &MockRepository_GetPlan_Call{Call: _e.mock.On("GetPlan", ctx, id)}
}

func (_c *MockRepository_GetPlan_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_GetPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetPlan_Call) Return(plan store.Plan, err error) *MockRepository_GetPlan_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockRepository_GetPlan_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (store.Plan, error)) *MockRepository_GetPlan_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlans provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPlans(ctx context.Context) ([]store.Plan, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlans")
	}

	var r0 []store.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]store.Plan, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []store.Plan); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Plan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlans'
type MockRepository_ListPlans_Call struct {
	*mock.Call
}

// ListPlans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ListPlans(ctx interface{}) *MockRepository_ListPlans_Call {
	return &MockRepository_ListPlans_Call{Call: _e.mock.On("ListPlans", ctx)}
}

func (_c *MockRepository_ListPlans_Call) Run(run func(ctx context.Context)) *MockRepository_ListPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListPlans_Call) Return(plans []store.Plan, err error) *MockRepository_ListPlans_Call {
	_c.Call.Return(plans, err)
	return _c
}

func (_c *MockRepository_ListPlans_Call) RunAndReturn(run func(ctx context.Context) ([]store.Plan, error)) *MockRepository_ListPlans_Call {
	_c.Call.Return(run)
	return _c
}
