// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Plan struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Provider    string
	ExternalID  string
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}
