// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plan (name, description)
VALUES ($1, $2)
`

type CreatePlanParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.Exec(ctx, createPlan, arg.Name, arg.Description)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plan WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, description, provider, external_id, is_active, created_at FROM plan WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id int32) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Provider,
		&i.ExternalID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, description, provider, external_id, is_active, created_at FROM plan ORDER BY id
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Provider,
			&i.ExternalID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plan
SET
    name = $1,
    description = $2
WHERE id = $3
RETURNING id, name, description, provider, external_id, is_active, created_at
`

type UpdatePlanParams struct {
	Name        string
	Description pgtype.Text
	ID          int32
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan, arg.Name, arg.Description, arg.ID)
	return err
}
