// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Plan struct {
	ID          pgtype.UUID
	Name        string
	Description string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
}

type Price struct {
	PlanID         pgtype.UUID
	Provider       string
	ProviderPlanID string
	CachedResponse []byte
	LastSyncedAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}
