// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plan (id, name, description, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, is_active, created_at
`

type CreatePlanParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	IsActive    bool
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createPrice = `-- name: CreatePrice :one
INSERT INTO price (
    plan_id,
    provider,
    provider_plan_id,
    cached_response,
    last_synced_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING plan_id, provider, provider_plan_id, cached_response, last_synced_at, created_at
`

type CreatePriceParams struct {
	PlanID         pgtype.UUID
	Provider       string
	ProviderPlanID string
	CachedResponse []byte
	LastSyncedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, createPrice,
		arg.PlanID,
		arg.Provider,
		arg.ProviderPlanID,
		arg.CachedResponse,
		arg.LastSyncedAt,
	)
	var i Price
	err := row.Scan(
		&i.PlanID,
		&i.Provider,
		&i.ProviderPlanID,
		&i.CachedResponse,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plan WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const deletePrice = `-- name: DeletePrice :exec
DELETE FROM price WHERE plan_id = $1 AND provider = $2 AND provider_plan_id = $3
`

type DeletePriceParams struct {
	PlanID         pgtype.UUID
	Provider       string
	ProviderPlanID string
}

func (q *Queries) DeletePrice(ctx context.Context, arg DeletePriceParams) error {
	_, err := q.db.Exec(ctx, deletePrice, arg.PlanID, arg.Provider, arg.ProviderPlanID)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, description, is_active, created_at FROM plan WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPricesByPlan = `-- name: GetPricesByPlan :many
SELECT plan_id, provider, provider_plan_id, cached_response, last_synced_at, created_at FROM price WHERE plan_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetPricesByPlan(ctx context.Context, planID pgtype.UUID) ([]Price, error) {
	rows, err := q.db.Query(ctx, getPricesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Price
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.PlanID,
			&i.Provider,
			&i.ProviderPlanID,
			&i.CachedResponse,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, description, is_active, created_at FROM plan
ORDER BY created_at DESC
OFFSET $1 LIMIT $2
`

type ListPlansParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plan
SET
    name = $1,
    description = $2,
    is_active = $3
WHERE id = $4
RETURNING id, name, description, is_active, created_at
`

type UpdatePlanParams struct {
	Name        string
	Description string
	IsActive    bool
	ID          pgtype.UUID
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
